"""add reopen requests table

Revision ID: 6d0df8bd3d14
Revises: 318ba5e831e7
Create Date: 2026-08-22 15:37:41.987864

Milestone 18, Phase 5: citizen reopening requests.

Adds a new, independent `reopen_requests` table -- no existing table is
altered. A citizen's reopen request is a REQUEST for authority action,
never a direct status change; the actual Issue.status transition
(RESOLVED -> REOPENED on approval) still goes through the existing
lifecycle mechanism and is recorded exactly once in the existing
issue_status_history table, not duplicated here.

Generated via `alembic revision --autogenerate` against the real ORM
model (backend/models.py's ReopenRequest) to guarantee the schema here
matches Base.metadata exactly -- verified with `alembic check` after
applying.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d0df8bd3d14'
down_revision: Union[str, None] = '318ba5e831e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reopen_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('citizen_reason', sa.Text(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='reopenrequeststate', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reopen_requests_issue_id'), 'reopen_requests', ['issue_id'], unique=False)
    op.create_index(op.f('ix_reopen_requests_public_id'), 'reopen_requests', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reopen_requests_public_id'), table_name='reopen_requests')
    op.drop_index(op.f('ix_reopen_requests_issue_id'), table_name='reopen_requests')
    op.drop_table('reopen_requests')
    # ### end Alembic commands ###
