"""add issue status history table

Revision ID: ae85602c974c
Revises: b7da687043fd
Create Date: 2026-08-20 10:20:25.163311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae85602c974c'
down_revision: Union[str, None] = 'b7da687043fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('SUBMITTED', 'CLASSIFIED', 'ROUTED', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'REJECTED', 'REOPENED', name='issue_status_history_from_status', create_constraint=True), nullable=True),
    sa.Column('to_status', sa.Enum('SUBMITTED', 'CLASSIFIED', 'ROUTED', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'REJECTED', 'REOPENED', name='issue_status_history_to_status', create_constraint=True), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_status_history_issue_id'), 'issue_status_history', ['issue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_status_history_issue_id'), table_name='issue_status_history')
    op.drop_table('issue_status_history')
    # ### end Alembic commands ###
