"""create issues table

Revision ID: b7da687043fd
Revises: 
Create Date: 2026-08-20 09:27:22.794657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7da687043fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('STREET_LIGHTING', 'ROADS_AND_POTHOLES', 'WATER_SUPPLY', 'SEWAGE_AND_DRAINAGE', 'SANITATION_AND_WASTE', 'ELECTRICITY', 'PUBLIC_SAFETY', 'PUBLIC_TRANSPORT', 'PARKS_AND_PUBLIC_SPACES', 'NOISE_POLLUTION', 'ILLEGAL_CONSTRUCTION', 'STRAY_ANIMALS', 'OTHER', name='issue_category', create_constraint=True), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', 'UNKNOWN', name='issue_severity', create_constraint=True), nullable=False),
    sa.Column('affected_population', sa.String(length=255), nullable=True),
    sa.Column('suggested_department', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('assigned_department', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'CLASSIFIED', 'ROUTED', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'REJECTED', 'REOPENED', name='issue_status', create_constraint=True), nullable=False),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_public_id'), 'issues', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issues_public_id'), table_name='issues')
    op.drop_table('issues')
    # ### end Alembic commands ###
